package com.ms7.msnet

enum class Lang { EN, FA }

private val faDigits = charArrayOf('၀','၁','၂','၃','၄','၅','၆','၇','၈','၉')

fun localizeDigits(text: String, lang: Lang): String {
    if (lang != Lang.FA) return text
    val sb = StringBuilder(text.length)
    for (c in text) sb.append(if (c in '0'..'9') faDigits[c - '0'] else c)
    return sb.toString()
}
object Strings {

    private val en = mapOf(
        "connection" to "Connection",
        "settings" to "Settings",
        "app_title" to "GRoute",
        "appearance" to "Appearance",
        "choose_server" to "Choose server",
        "add_config_title" to "Add config",
        "data_usage" to "Data usage",
        "selected_server" to "Selected server",
        "tap_choose" to "Tap to choose a server",
        "connect" to "Connect",
        "connecting_cancel" to "Connecting…  (tap to cancel)",
        "disconnect" to "Disconnect",
        "real_delay" to "Ping",
        "speed_test" to "Speed test",
        "testing" to "Testing…",
        "delay_failed" to "Timeout",
        "speed_failed" to "Speed: failed",
        "status_disconnected" to "Disconnected",
        "conn_disconnected" to "Disconnected",
        "conn_connected_for" to "Connected for %s",
        "status_connecting" to "Connecting…",
        "status_connected" to "Connected",
        "status_error" to "Error",
        "paste_links" to "Paste one or many links (one per line)",
        "add" to "Add",
        "paste_clipboard" to "Paste from clipboard",
        "add_manually" to "Add manually",
        "add_warp" to "Add WARP",
        "warp_added" to "WARP added",
        "warp_failed" to "WARP sign-up failed",
        "scan_warp" to "Scan Cloudflare IPs",
        "scan_title" to "Cloudflare IP scanner",
        "scan_sub" to "Find clean Cloudflare edge IPs that work here",
        "scan_intro" to "Samples Cloudflare's IP ranges and keeps the ones reachable from your network, ranked by latency. Tap an IP to copy it — use it as a clean IP for Cloudflare-fronted servers.",
        "scan_count" to "How many IPs to scan",
        "scan_start" to "Start scan",
        "scanning" to "Scanning…",
        "scan_done" to "%d clean IPs found",
        "scan_none" to "No reachable IPs found — scan again",
        "copy_all" to "Copy all",
        "copied" to "Copied",
        "copied_all" to "All IPs copied",
        "tools" to "Tools",
        "test_all" to "Test all",
        "test_completed" to "Test completed",
        "adding" to "Adding…",
        "added_configs" to "Added %d config(s)",
        "added_sub" to "Added a sub with %d configs",
        "clipboard_empty" to "Clipboard is empty",
        "pasted" to "Pasted from clipboard",
        "manual_configs" to "Manual configs",
        "refresh" to "Refresh",
        "remove" to "Remove",
        "delete" to "Delete",
        "edit" to "Edit",
        "share" to "Share",
        "share_clipboard" to "Share to clipboard",
        "share_app" to "Share to app",
        "share_file" to "Share as file",
        "show" to "Show",
        "export_title" to "Export config",
        "export_title_multi" to "Export configs",
        "export_file_name" to "File name",
        "export_password" to "Password (optional)",
        "export_password_hint" to "Leave empty for no password",
        "export_encrypted_note" to "Files are encrypted with AES-256 and can only be opened inside GRoute.",
        "export_locked_note" to "Imported configs are protected: their details can't be viewed or edited, but you can rename them.",
        "export_continue" to "Choose where to share",
        "export_count" to "%d configs will be exported",
        "import_title" to "Import config file",
        "import_password" to "Enter file password",
        "import_wrong_password" to "Wrong password",
        "import_needs_password" to "This file is password protected",
        "import_bad_file" to "This file is invalid or damaged",
        "import_foreign_app" to "This file was made by a different build of GRoute",
        "import_success" to "%d configs imported",
        "import_open" to "Open",
        "import_button" to "Import",
        "locked_config" to "Protected config",
        "locked_note" to "This config is protected. You can only change its name.",
        "selected" to "selected",
        "delete_selected_q" to "Delete the selected configs?",
        "copied" to "Copied to clipboard",
        "edit_config_title" to "Edit config",
        "edit_sub_name" to "Edit name",
        "service_name" to "gRPC service name",
        "mode" to "Mode",
        "alpn" to "ALPN (comma-separated)",
        "fingerprint" to "Fingerprint",
        "xray_logs" to "Xray logs",
        "xray_logs_sub" to "View the engine’s runtime logs",
        "clear" to "Clear",
        "no_logs" to "No logs yet",
        "stab_title" to "Internet Quality Test",
        "stab_sub" to "Speed, ping, jitter and quality rating",
        "stab_start" to "Start test",
        "stab_ping" to "Ping",
        "stab_dl_ping" to "Download ping",
        "stab_ul_ping" to "Upload ping",
        "stab_jitter" to "Jitter",
        "stab_idle_latency" to "Idle latency",
        "stab_dl_latency" to "Download latency",
        "stab_ul_latency" to "Upload latency",
        "stab_direct_checking" to "Checking direct network\u2026",
        "stab_direct_stable" to "Direct network is stable",
        "stab_direct_unstable" to "Direct network is unstable",
        "stab_direct_offline" to "Internet connection is off",
        "stab_last_test" to "Last test:",
        "stab_quality" to "Quality",
        "stab_gaming" to "Gaming",
        "stab_browsing" to "Web browsing",
        "stab_streaming" to "Streaming",
        "stab_calling" to "Video calling",
        "stab_through_tunnel" to "Testing through the tunnel",
        "stab_direct" to "Testing your direct connection",
        "stab_failed" to "Test failed — check your connection",
        "stab_testing_server" to "Testing server:",
        "stab_no_server" to "Select a server to test",
        "default_order" to "Default order",
        "fastest_first" to "Fastest first",
        "routing" to "Routing",
        "split_title" to "Split routing",
        "split_sub" to "Myanmar websites bypass the tunnel and connect directly.",
        "fragment_title" to "Fragment (anti-DPI)",
        "fragment_sub" to "Splits the TLS handshake to evade SNI filtering. Try it if a server won't connect.",
        "sniffing_title" to "Turn on Sniffing",
        "sniffing_type" to "Sniffing type",
        "sniffing_sub" to "Connects using the domain detected from traffic instead of the raw IP. Can help some servers connect correctly.",
        "kill_switch_title" to "Kill switch",
        "mux_title" to "Mux (multiplexing)",
        "mux_sub" to "Sends multiple connections through one stream. Can help on restrictive networks, but may reduce speed. Leave off with Reality/Vision.",
        "mux_concurrency" to "Max concurrent streams",
        "kill_switch_sub" to "Blocks all internet if the VPN drops unexpectedly, so your traffic never leaks. Tap disconnect to restore.",
        "always_on_title" to "Enable system lockdown",
        "always_on_sub" to "For a fully leak-proof kill switch, turn on \"Always-on VPN\" and \"Block connections without VPN\" for GRoute in system settings.",
        "globe_style_title" to "Globe style",
        "globe_style_filled" to "Filled",
        "globe_style_dots" to "Dots",
        "theme_settings" to "Theme settings",
        "theme_settings_sub" to "Appearance, colors and globe style",
        "theme_mode" to "Theme",
        "theme_light" to "Light",
        "theme_dark" to "Dark",
        "theme_amoled" to "AMOLED black",
        "theme_system" to "Follow system",
        "takes_effect" to "Changes take effect on the next connection.",
        "language" to "Language",
        "about" to "About",
        "about_sub" to "Version, developer & privacy policy",
        "app_version" to "App version",
        "xray_version" to "Xray core",
        "telegram_support" to "Telegram support",
        "privacy_policy" to "Privacy Policy",
        "developer" to "Developer",
        "source_code" to "Source code",
        "check_updates" to "Check for updates",
        "checking_updates" to "Checking…",
        "up_to_date" to "You're on the latest version",
        "update_available" to "Update available: %s",
        "update_failed" to "Couldn't check — try again",
        "update_now" to "Update",
        "later" to "Later",
        "auto_refresh" to "Auto-refresh subscriptions",
        "auto_refresh_off" to "Off",
        "every_hour" to "Every %s hour",
        "every_hours" to "Every %s hours",
        "all_time_total" to "All-time total",
        "tap_ranges" to "Tap for ranges and custom dates  ›",
        "range" to "Range",
        "today" to "Today",
        "range_7d" to "7d",
        "range_30d" to "30d",
        "custom_range" to "Custom range",
        "from" to "From",
        "to" to "To",
        "custom_hint" to "Up to 2 days shows hourly detail; longer shows daily. Hourly history is kept ~30 days.",
        "download" to "Download",
        "upload" to "Upload",
        "total" to "Total",
        "no_data_range" to "No data for this range.",
        "tunnel_only" to "Counts only traffic sent through the tunnel.",
        "peak_per_bar" to "Peak %s per bar",
        "name_optional" to "Name (optional)",
        "protocol" to "Protocol",
        "address" to "Address",
        "port" to "Port",
        "uuid" to "UUID",
        "password" to "Password",
        "enc_method" to "Encryption method",
        "flow_optional" to "Flow (optional)",
        "network" to "Network",
        "security" to "Security",
        "sni" to "SNI / server name",
        "public_key" to "Public key (pbk)",
        "short_id" to "Short ID (sid)",
        "ws_path" to "WS path",
        "ws_host" to "WS host header",
        "cancel" to "Cancel",
        "save" to "Save",
        "err_address" to "Address is required",
        "err_port" to "Port must be 1–65535",
        "err_uuid" to "UUID is required",
        "err_password" to "Password is required",
        "fetching_sub" to "Fetching subscription…",
        "no_configs" to "No configs found",
        "fetch_failed" to "Fetch failed",
        "parse_none" to "Couldn't parse any links",
        "left" to "left",
        "of" to "of",
        "expires_in" to "expires in",
        "unit_b" to "B",
        "unit_kb" to "KB",
        "unit_mb" to "MB",
        "unit_gb" to "GB",
        "unit_ms" to "ms",
        "unit_mbps" to "Mbps",
        "unit_per_sec" to "/s",
        "unit_days" to "d",
        "welcome_tagline" to "Fast • Secure • Stable",
        "welcome_dev" to "Developed by MS7",
        "per_app" to "Per-app proxy",
        "per_app_sub" to "Choose which apps use the VPN",
        "per_app_mode" to "Mode",
        "per_app_off" to "Off (all apps use VPN)",
        "per_app_allow" to "Only selected apps",
        "per_app_block" to "All apps except selected",
        "per_app_off_hint" to "Per-app routing is off — every app uses the VPN.",
        "search_apps" to "Search apps",
        "loading_apps" to "Loading apps…"
    )

    private val fa = mapOf(
       "connection" to "ချိတ်ဆက်မှု",
"settings" to "ဆက်တင်များ",
"app_title" to "MSNet",
"choose_server" to "ဆာဗာရွေးချယ်ရန်",
"add_config_title" to "ကွန်ဖစ်ထည့်ရန်",
"data_usage" to "ဒေတာအသုံးပြုမှု",
"selected_server" to "ရွေးချယ်ထားသော ဆာဗာ",
"tap_choose" to "ဆာဗာရွေးရန် နှိပ်ပါ",
"connect" to "ချိတ်ဆက်ရန်",
"connecting_cancel" to "ချိတ်ဆက်နေသည်... (ပယ်ဖျက်ရန် နှိပ်ပါ)",
"disconnect" to "ချိတ်ဆက်မှုဖြုတ်ရန်",
"real_delay" to "Ping",
"speed_test" to "အမြန်နှုန်းစမ်းသပ်ရန်",
"testing" to "စမ်းသပ်နေသည်...",
"delay_failed" to "အချိန်ကျော်လွန်သွားသည်",
"speed_failed" to "အမြန်နှုန်း စမ်းသပ်မှု မအောင်မြင်ပါ",
"status_disconnected" to "မချိတ်ဆက်ရသေးပါ",
"conn_disconnected" to "ချိတ်ဆက်မှု ဖြုတ်ထားသည်",
"conn_connected_for" to "%s ကြာ ချိတ်ဆက်ထားသည်",
"status_connecting" to "ချိတ်ဆက်နေသည်...",
"status_connected" to "ချိတ်ဆက်ထားသည်",
"status_error" to "အမှား",
"paste_links" to "Link တစ်ခု သို့မဟုတ် အများအပြား ထည့်ပါ (တစ်ကြောင်းလျှင် တစ်ခု)",
"add" to "ထည့်ရန်",
"paste_clipboard" to "Clipboard မှ ထည့်ရန်",
"add_manually" to "ကိုယ်တိုင်ထည့်ရန်",
"add_warp" to "WARP ထည့်ရန်",
"warp_added" to "WARP ထည့်ပြီးပါပြီ",
"warp_failed" to "WARP ထည့်၍ မရပါ",
"scan_warp" to "Cloudflare IP များ စစ်ဆေးရန်",
"scan_title" to "Cloudflare IP Scanner",
"scan_sub" to "သင့်ကွန်ရက်တွင် အသုံးပြုနိုင်သော Cloudflare Edge IP များကို ရှာဖွေပါ",
"scan_intro" to "Cloudflare IP Range များကို စစ်ဆေးပြီး Ping အနည်းဆုံး IP များကို စီစဉ်ပြသပေးသည်။ IP ကိုနှိပ်၍ ကူးယူနိုင်ပြီး Cloudflare Proxy အသုံးပြုသော Server များတွင် Clean IP အဖြစ် အသုံးပြုနိုင်သည်။",
"scan_count" to "စစ်ဆေးမည့် IP အရေအတွက်",
"scan_start" to "စတင်စစ်ဆေးရန်",
"scanning" to "စစ်ဆေးနေသည်...",
"scan_done" to "အသုံးပြုနိုင်သော IP %d ခု တွေ့ရှိသည်",
"scan_none" to "အသုံးပြုနိုင်သော IP မတွေ့ပါ — ထပ်မံစစ်ဆေးပါ",
"copy_all" to "အားလုံးကူးယူရန်",
"copied" to "ကူးယူပြီးပါပြီ",
"copied_all" to "IP အားလုံး ကူးယူပြီးပါပြီ",
"tools" to "ကိရိယာများ",
"test_all" to "အားလုံးစမ်းသပ်ရန်",
"test_completed" to "စမ်းသပ်မှု ပြီးဆုံးပါပြီ",
"adding" to "ထည့်သွင်းနေသည်...",
"added_configs" to "Config %d ခု ထည့်ပြီးပါပြီ",
"added_sub" to "Config %d ခုပါသော Subscription ကို ထည့်ပြီးပါပြီ",
"clipboard_empty" to "Clipboard ဗလာဖြစ်နေသည်",
"pasted" to "Clipboard မှ ထည့်ပြီးပါပြီ",
"manual_configs" to "Manual Config များ",
"refresh" to "ပြန်လည်ရယူရန်",
"remove" to "ဖယ်ရှားရန်",
"delete" to "ဖျက်ရန်",
"edit" to "ပြင်ဆင်ရန်",
"share" to "မျှဝေရန်",
"share_clipboard" to "Clipboard သို့ မျှဝေရန်",
"share_app" to "App ဖြင့် မျှဝေရန်",
"share_file" to "ဖိုင်အဖြစ် မျှဝေရန်",
"show" to "ပြရန်",
"export_title" to "Config Export",
"export_title_multi" to "Config များ Export",
"export_file_name" to "ဖိုင်အမည်",
"export_password" to "စကားဝှက် (လိုအပ်ပါက)",
"export_password_hint" to "စကားဝှက်မထားလိုပါက ဗလာထားပါ",
"export_encrypted_note" to "ဖိုင်များကို AES-256 ဖြင့် လုံခြုံစွာ Encrypt လုပ်ထားမည်ဖြစ်ပြီး MSNet တွင်သာ ဖွင့်နိုင်ပါသည်။",
"export_locked_note" to "Import လုပ်ထားသော Config များကို ကြည့်ရှုခြင်းနှင့် ပြင်ဆင်ခြင်း မပြုနိုင်ပါ။ အမည်ကိုသာ ပြောင်းနိုင်သည်။",
"export_continue" to "မျှဝေမည့်နေရာကို ရွေးချယ်ပါ",         
    "export_count" to "Config %d ခု Export ပြုလုပ်မည်",
"import_title" to "Config ဖိုင် ထည့်သွင်းရန်",
"import_password" to "ဖိုင်၏ စကားဝှက်ကို ထည့်ပါ",
"import_wrong_password" to "စကားဝှက် မှားနေပါသည်",
"import_needs_password" to "ဤဖိုင်တွင် စကားဝှက် လိုအပ်သည်",
"import_bad_file" to "ဖိုင်သည် မမှန်ကန်ပါ သို့မဟုတ် ပျက်စီးနေသည်",
"import_foreign_app" to "ဤဖိုင်ကို MSNet ၏ အခြားဗားရှင်းဖြင့် ဖန်တီးထားသည်",
"import_success" to "Config %d ခု ထည့်သွင်းပြီးပါပြီ",
"import_open" to "ဖွင့်ရန်",
"import_button" to "ထည့်သွင်းရန်",
"locked_config" to "ကာကွယ်ထားသော Config",
"locked_note" to "ဤ Config ကို ကာကွယ်ထားပါသည်။ အမည်ကိုသာ ပြောင်းနိုင်ပါသည်။",
"selected" to "ရွေးချယ်ထားသည်",
"delete_selected_q" to "ရွေးချယ်ထားသော Config များကို ဖျက်မလား?",
"edit_config_title" to "Config ပြင်ဆင်ရန်",
"edit_sub_name" to "အမည်ပြင်ရန်",
"service_name" to "gRPC Service အမည်",
"mode" to "Mode",
"alpn" to "ALPN (Comma ဖြင့် ခွဲပါ)",
"fingerprint" to "Fingerprint",
"xray_logs" to "Xray Logs",
"xray_logs_sub" to "Engine Runtime Logs များ ကြည့်ရှုရန်",
"clear" to "ရှင်းလင်းရန်",
"no_logs" to "Log မရှိသေးပါ",
"stab_title" to "အင်တာနက် အရည်အသွေး စမ်းသပ်ခြင်း",
"stab_sub" to "Speed၊ Ping၊ Jitter နှင့် အရည်အသွေး",
"stab_start" to "စတင်စမ်းသပ်ရန်",
"stab_ping" to "Ping",
"stab_dl_ping" to "Download Ping",
"stab_ul_ping" to "Upload Ping",
"stab_jitter" to "Jitter",
"stab_idle_latency" to "Idle Latency",
"stab_dl_latency" to "Download Latency",
"stab_ul_latency" to "Upload Latency",
"stab_direct_checking" to "တိုက်ရိုက်ကွန်ရက်ကို စစ်ဆေးနေသည်...",
"stab_direct_stable" to "တိုက်ရိုက်ကွန်ရက် တည်ငြိမ်သည်",
"stab_direct_unstable" to "တိုက်ရိုက်ကွန်ရက် မတည်ငြိမ်ပါ",
"stab_direct_offline" to "အင်တာနက် ချိတ်ဆက်မှု မရှိပါ",
"stab_last_test" to "နောက်ဆုံး စမ်းသပ်မှု:",
"stab_quality" to "အရည်အသွေး",
"stab_gaming" to "ဂိမ်းကစားခြင်း",
"stab_browsing" to "ဝဘ်အသုံးပြုခြင်း",
"stab_streaming" to "ဗီဒီယိုကြည့်ရှုခြင်း",
"stab_calling" to "ဗီဒီယိုခေါ်ဆိုမှု",
"stab_through_tunnel" to "Tunnel မှတစ်ဆင့် စမ်းသပ်ရန်",
"stab_direct" to "တိုက်ရိုက် ချိတ်ဆက်မှု စမ်းသပ်ရန်",
"stab_failed" to "စမ်းသပ်မှု မအောင်မြင်ပါ — သင့်အင်တာနက်ကို စစ်ဆေးပါ",
"stab_testing_server" to "စမ်းသပ်မည့် Server:",
"stab_no_server" to "စမ်းသပ်ရန် Server တစ်ခု ရွေးချယ်ပါ",
"default_order" to "မူလအစီအစဉ်",
"fastest_first" to "အမြန်ဆုံးကို အရင်ပြရန်",
"routing" to "Routing",
"split_title" to "Split Routing (မြန်မာ Website များကို တိုက်ရိုက်ချိတ်ဆက်ရန်)",
"split_sub" to "သတ်မှတ်ထားသော Website များကို VPN မသုံးဘဲ တိုက်ရိုက် ချိတ်ဆက်ပေးသည်။",
"fragment_title" to "Fragment (Anti-DPI)",
"fragment_sub" to "TLS Handshake ကို ခွဲပေးခြင်းဖြင့် DPI Filtering ကို ကျော်လွှားနိုင်သည်။ Server မချိတ်ဆက်နိုင်ပါက စမ်းသုံးကြည့်ပါ။",
"sniffing_title" to "Sniffing ဖွင့်ရန်",
"sniffing_type" to "Sniffing အမျိုးအစား",
"sniffing_sub" to "Raw IP အစား Domain ကို အသုံးပြု၍ ချိတ်ဆက်ပေးသည်။ အချို့ Server များတွင် ချိတ်ဆက်မှု ပိုကောင်းစေနိုင်သည်။",
"kill_switch_title" to "Kill Switch",
"mux_title" to "Mux (Multiplexing)",
"mux_sub" to "Connection အများအပြားကို Stream တစ်ခုတည်းဖြင့် ပို့ပေးသည်။ Filtering များသောနေရာတွင် အထောက်အကူပြုနိုင်သော်လည်း မြန်နှုန်း လျော့နိုင်သည်။ Reality/Vision အသုံးပြုလျှင် ပိတ်ထားရန် အကြံပြုသည်။",
"mux_concurrency" to "တစ်ပြိုင်နက် Stream အများဆုံး",
"kill_switch_sub" to "VPN ရုတ်တရက် ပြတ်တောက်သွားပါက သင့် IP မပေါက်ကြားစေရန် အင်တာနက်ကို အလိုအလျောက် ပိတ်ပေးသည်။",
"always_on_title" to "System Lock ဖွင့်ရန်",
"always_on_sub" to "Android Settings တွင် 'Always-on VPN' နှင့် 'Block connections without VPN' ကို MSNet အတွက် ဖွင့်ထားပါ။",
"globe_style_title" to "ကမ္ဘာလုံး ပုံစံ",
"globe_style_filled" to "အပြည့်",
"globe_style_dots" to "အစက်များ",
"theme_settings" to "အသွင်အပြင် ဆက်တင်များ",
"theme_settings_sub" to "Theme၊ အရောင်များနှင့် ကမ္ဘာလုံးပုံစံ",
"theme_mode" to "Theme",
"theme_light" to "အလင်း",
"theme_dark" to "အမှောင်",
"theme_amoled" to "AMOLED အနက်",
"theme_system" to "စနစ်အတိုင်း",
        "takes_effect" to "အပြောင်းအလဲများကို နောက်တစ်ကြိမ် ချိတ်ဆက်သည့်အခါ အသက်ဝင်မည်။",
"language" to "ဘာသာစကား",
"about" to "အကြောင်း",
"about_sub" to "ဗားရှင်း၊ Developer နှင့် ကိုယ်ရေးကိုယ်တာ မူဝါဒ",
"app_version" to "App ဗားရှင်း",
"xray_version" to "Xray Core",
"telegram_support" to "Telegram အကူအညီ",
"privacy_policy" to "ကိုယ်ရေးကိုယ်တာ မူဝါဒ",
"developer" to "Developer",
"source_code" to "Source Code",
"check_updates" to "အပ်ဒိတ် စစ်ဆေးရန်",
"checking_updates" to "စစ်ဆေးနေသည်...",
"up_to_date" to "နောက်ဆုံးဗားရှင်းကို အသုံးပြုနေပါသည်",
"update_available" to "အပ်ဒိတ်အသစ် ရရှိနိုင်ပါသည်: %s",
"update_failed" to "စစ်ဆေးမှု မအောင်မြင်ပါ — ထပ်မံကြိုးစားပါ",
"update_now" to "ယခု အပ်ဒိတ်လုပ်ရန်",
"later" to "နောက်မှ",
"auto_refresh" to "Subscription များကို အလိုအလျောက် Refresh လုပ်ရန်",
"auto_refresh_off" to "ပိတ်ထားသည်",
"every_hour" to "%s နာရီတိုင်း",
"every_hours" to "%s နာရီတိုင်း",
"all_time_total" to "စုစုပေါင်း",
"tap_ranges" to "အချိန်ကာလ ရွေးချယ်ရန် နှိပ်ပါ ›",
"range" to "အချိန်ကာလ",
"today" to "ယနေ့",
"range_7d" to "၇ ရက်",
"range_30d" to "၃၀ ရက်",
"custom_range" to "စိတ်ကြိုက်ကာလ",
"from" to "မှ",
"to" to "အထိ",
"custom_hint" to "၂ ရက်အထိ နာရီအလိုက် ပြသမည်။ ထို့ထက်ကျော်လွန်ပါက ရက်အလိုက် ပြသမည်။",
"download" to "ဒေါင်းလုဒ်",
"upload" to "အပ်လုဒ်",
"total" to "စုစုပေါင်း",
"no_data_range" to "ဤအချိန်ကာလအတွက် ဒေတာမရှိပါ။",
"tunnel_only" to "VPN Tunnel မှ ဖြတ်သန်းသော Traffic ကိုသာ တွက်ချက်သည်။",
"peak_per_bar" to "Bar တစ်ခုစီ၏ အမြင့်ဆုံး %s",
"name_optional" to "အမည် (မဖြည့်လည်းရသည်)",
"protocol" to "Protocol",
"address" to "လိပ်စာ",
"port" to "Port",
"uuid" to "UUID",
"password" to "စကားဝှက်",
"enc_method" to "Encryption Method",
"flow_optional" to "Flow (မဖြည့်လည်းရသည်)",
"network" to "ကွန်ရက်",
"security" to "လုံခြုံရေး",
"sni" to "SNI / Server Name",
"public_key" to "Public Key (pbk)",
"short_id" to "Short ID (sid)",
"ws_path" to "WS Path",
"ws_host" to "WS Host Header",
"cancel" to "ပယ်ဖျက်ရန်",
"save" to "သိမ်းရန်",
"err_address" to "လိပ်စာ ဖြည့်ရန်လိုအပ်သည်",
"err_port" to "Port သည် 1 မှ 65535 အတွင်း ဖြစ်ရမည်",
"err_uuid" to "UUID ဖြည့်ရန်လိုအပ်သည်",
"err_password" to "စကားဝှက် ဖြည့်ရန်လိုအပ်သည်",
"fetching_sub" to "Subscription ရယူနေသည်...",
"no_configs" to "Config မတွေ့ပါ",
"fetch_failed" to "ရယူမှု မအောင်မြင်ပါ",
"parse_none" to "အသုံးပြုနိုင်သော Link မတွေ့ပါ",
"left" to "ကျန်ရှိ",
"of" to "/",
"expires_in" to "သက်တမ်းကုန်ရန်",
"unit_b" to "Bytes",
"unit_kb" to "KB",
"unit_mb" to "MB",
"unit_gb" to "GB",
"unit_ms" to "ms",
"unit_mbps" to "Mbps",
"unit_per_sec" to "/sec",
"unit_days" to "ရက်",
"welcome_tagline" to "မြန်ဆန် • လုံခြုံ • တည်ငြိမ်",
"welcome_dev" to "Developed by MS7",
"per_app" to "App အလိုက် Proxy",
"per_app_sub" to "VPN အသုံးပြုမည့် App များကို ရွေးချယ်ပါ",
"per_app_mode" to "Mode",
"per_app_off" to "ပိတ်ထားသည် (App အားလုံး)",
"per_app_allow" to "ရွေးချယ်ထားသော App များသာ",
"per_app_block" to "ရွေးချယ်ထားသော App များမှလွဲ၍ အားလုံး",
"per_app_off_hint" to "Per-App Routing ပိတ်ထားသည် — App အားလုံး VPN ကို အသုံးပြုမည်။",
"search_apps" to "App ရှာရန်",
"loading_apps" to "App များကို ဖွင့်နေသည်...",
        )

    fun get(lang: Lang, key: String): String =
        (if (lang == Lang.FA) fa[key] else en[key]) ?: en[key] ?: key
}
